spring:
  rabbitmq:
    adresses: localhost:5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s #Explicações na aula 47, minuto 12:00. Retry Mechanism de forma simples!
          max-attempts: 5
          multiplier: 2
